Correct handling of StgDict/StgInfo for Structure return types
beeware/rubicon-objc pull request #446
Opened 2024-04-16 06:35 UTC by freakboy3742

Fixes #444.

python/cpython#114314 replaced the StgDict structure with StgInfo; this has been released in Python 3.13.0a6. 

The real fix for this is to address this upstream, rather than requiring us to work around ctypes; but:

1. Working up this patch was helpful in understanding how the new StgInfo structure works
2. Until such time as a patch is merged upstream, we need a workaround so that Rubicon's tests pass.

Although the patch looks like a lot of code, most of the delta is actually a re-org so that the older code will be auto removed when Py3.13 is the oldest supported version.

As a test, I've also run the full Toga testbed on macOS with this code and it worked as expected.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

2024-04-16 08:02 UTC, dgelessus requested changes
Thank you for taking care of this!

2024-04-16 08:02 UTC, dgelessus commented on src/rubicon/objc/ctypes_patch.py
> +        return StgInfo.from_address(id(tp) + py_type_type.tp_basicsize)
After obtaining the `StgInfo`, we should also check that its `initialized` field is non-zero, like the real code in CPython does.

2024-04-16 10:04 UTC, mhsmith commented
I'm not familiar with this area, so I'll leave the reviewing to others.

2024-04-16 19:41 UTC, samschott reviewed
Thanks for the fix, and the very well documented code! Pending the requested changes by @dgelessus, this looks good to me.

2024-04-17 20:10 UTC, samschott requested changes

2024-04-18 02:24 UTC, freakboy3742 commented on src/rubicon/objc/ctypes_patch.py
> +            id(type(ctypes.Structure).__base__),
The internal call that we're replicating is:

    PyObject_GetTypeData((PyObject *)type, state->PyCType_Type)

`type` is the base Python type, which has different handling. `type(tp)` is `_ctypes.PyCStructType`, which is a subclass of `_ctypes.PyCType_Type`, and has it's own type data.  `type(tp).__base__` resolves to `PyCType_Type` for a simple case, but if there's an inheritance chain in place, that won't be guaranteed; using `type(ctypes.Structure).__base__` guarantees we always get `PyCType_Type`.

I guess the real fix here is that the initial check on L207 isn't consistent with the original method - it should be checking `state->PyCType_Type` as well. I'll make that change, and added in references to the original code as well.

(The other answer, of course, is that using `id(type(tp))` or `id(type)` doesn't work at runtime, but `id(type(ctypes.Structure).__base__)` does 😄)

2024-04-18 18:46 UTC, samschott commented on src/rubicon/objc/ctypes_patch.py
> +            id(type(ctypes.Structure).__base__),
Thanks, and thanks for the explanation!

Btw, `id(type)` works just fine for me at runtime and `id(type(ctypes.Structure).__base__) == id(type)` evaluates to True.

2024-04-18 18:46 UTC, samschott approved these changes

2024-04-19 02:01 UTC, freakboy3742 commented on src/rubicon/objc/ctypes_patch.py
> +            id(type(ctypes.Structure).__base__),
Are you running your test on 3.13.0a6? `id(type(ctypes.Structure).__base__) == id(type)` definitely returns True on Python 3.10, 3.12, and presumably everything before 3.13.0a6, but it's False on 3.13.0a6; and if you're not on 3.13.0a6, the GetTypeData call won't be invoked at all.

2024-04-19 09:28 UTC, samschott commented on src/rubicon/objc/ctypes_patch.py
> +            id(type(ctypes.Structure).__base__),
Ohh, that explains it!

2024-04-22 00:45 UTC, freakboy3742 commented
@dgelessus Are you OK with this updated version?

2024-04-25 14:54 UTC, dgelessus approved these changes
LGTM as well. Thanks!

2024-04-25 22:04 UTC, merged